### PR TITLE
Add default resources

### PR DESCRIPTION
**Pull request by sjtoik**
ArangoDB doesn't have sane resources defined and fails to start in KaaS

### CODE REVIEW

**Review by SimonMisencik — COMMENTED** [review]
I would prefer to leave the resource setting as optional in these generic values. So something like this https://github.com/FRINXio/helm-charts/blob/main/charts/krakend/templates/deployment.yaml#L199 https://github.com/FRINXio/helm-charts/blob/main/charts/krakend/values.yaml#L54 ... so we can easily install frinx-machine in environments with little resources.

**Comment by sjtoik** [comment]
Resource request: this the minimum what I need to be able to run. This can be really low.
Resource limit: After this limit I'm not functioning correctly. OOMKill or throthling happens.

Overprovisioning can happen if the limit is higher than what the resource pool available. Every component should have these resource restrictions set. If not, you are saying you don't know how the system should behave.

**Comment by sjtoik** [comment]
With ArangoDB, the default configuration you are rocking with expects a certain amount of RAM. Application crashes without that sane definition because the container is given really tiny set by default.

**Comment by SimonMisencik** [comment]
This is what I was thinking about  https://github.com/FRINXio/helm-charts/pull/217/files. This recommendation is also written in the book written by helm maintainers: "When you run applications in production, it is a good practice to set resource limits. This prevents, for example, a memory leak in one container from disrupting other containers. When a chart author creates a chart that others are going to use, they may not know where it will be installed and how many resources will be available there. Could this be installed on a laptop by a developer or someone testing out the chart? Or, might this be installed on large production servers? To handle this variance in environment, the recommendation is to put in resource limits and then turn them into comments" BUTCHER, Matt; FARINA, Matt; DOLITSKY, Josh. Learning Helm. O'Reilly Media, 2021.

**Comment by SimonMisencik** [comment]
Stale PR

**Pull request closed without merging**
